name: Keep Alive

on:
  schedule:
    - cron: '0 0 */20 * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update timestamp
        run: date > keepalive.txt

      - name: Commit file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add keepalive.txt
          git commit -m "Keepalive commit" || exit 0
          git push
